version: '3'

services:
  graph_based:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - C_SOURCE_FILE=/cpu/mathematics/matrix_multiplication.c
    volumes:
      - .:/app
